### ISSUE TITLE
schema validity error - no visible elements in namespace

### ISSUE THREAD

**Issue by jvd10** [jvd10/apollo#1]
As of f397f66 the apollo_types_3.1.0.xsd can't be used to directly validate an instance of any type since no elements are defined in the schema (only complex type).

Motivation for this question is to be able to validate InfectiousDiseaseScenario documents against schema.  Simply wrapping the definition of the InfectiousDiseaseScenario complex type in an element produces the desired behavior.  See commit c66863ce5b6bd589fdd6469f1ef639c77e002aad for an example

Questions:
- Is there a specific reason that the elements are not exposed?
- Would making this change affect the work of others?
- Is there an alternative approach that should be used instead?

**Comment by JohnLevander** [comment]
Sorry, I didn't see this comment until I reviewed last week's meeting agenda. 

Please feel free to add the elements, we didn't have them because we didn't need them, but if you need them they won't hurt anything.

**Comment by jvd10** [comment]
Unsure if this was resolved or not; closing due to amount of time elapsed

**Comment by JohnLevander** [comment]
The new version (4.0.1) has elements defined.
